apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-app
  namespace: default
  labels:
    app: apache-app
    backstage.io/kubernetes-id: apache-app   #ğŸ”¹ Backstage Integration Label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-app
  template:
    metadata:
      labels:
        app: apache-app
        backstage.io/kubernetes-id: apache-app  #ğŸ”¹ Backstage Integration Label
    spec:
      containers:
      - name: apache-container
        image: httpd:latest
        ports:
        - containerPort: 80
